# image will be published to ghcr.io/<user>/<name>
name: atomic-server-common
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/ucore-minimal
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system 
          # in /usr/etc/ in the image. read more in files module reference.
  - type: rpm-ostree
    install:
      - wget # Dependency of COPR repos.

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - starship # Shell Prompt
      - nfs-utils # Fully featured nfs-utils - Dependency of libvirt
      - libvirt # Virtualization abstraction - Endpoint for terraform
      - qemu-kvm # Hypervisor
    remove:
      # Unneeded packages from ucore-minimal
      # Removed to minimize attack surface, reenable on a case by case basis
      - cockpit-bridge
      - cockpit-system
      - cockpit-selinux
      - cockpit-networkmanager
      - cockpit-podman
      - moby-engine
      - podman
      - podman-compose
      - toolbox
      - tailscale
      # END Unneeded packages from ucore-minimal END
      - nfs-utils-coreos # Replaced by fully featured `nfs-utils`

  - type: chezmoi
    source: "ghcr.io/exponentactivity/modules"
    # Installs chezmoi to /usr/bin/chezmoi from latest Github release
    # install_chezmoi: true # Optional - Default: true  - Expects type: boolean
    # () Git repository to initialize
    repository: "https://gitlab.com/unshippedreminder/dotfiles-server.git" # Required - Default: n/a  - Expects type: string
    # Enable the modules services globally for all users
    # enable_all_users: true # Optional - Default: true - Expects type: boolean
    # Dotfiles will be updated with this interval
    # run_every: '1d' # Optional - Default: '1d' - Expects type: string
    # Dotfile updates will wait this long after a boot before running
    # wait_after_boot: '5m' # Optional - Default: '5m' - Expects type: string
    # Disable the service that initializes `repository` on users that are logged in or has linger enabled
    # disable_init: false # Optional - Default: false - Expects type: boolean
    # Disable the timer that updates chezmoi with the interval set above
    # disable_update: false # Optional - Default: false - Expects type: boolean

  - type: script
    snippets:
      - "ln -sf /etc/firewalld/firewalld-atomicserver.conf /etc/firewalld/firewalld.conf"

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
