# image will be published to ghcr.io/<user>/<name>
name: atomic-server-customized
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/ucore-minimal
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system 
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
    remove:
      - cockpit-bridge # Unneeded package from ucore-minimal
      - cockpit-system # Unneeded package from ucore-minimal
      - cockpit-selinux # Unneeded package from ucore-minimal
      - cockpit-networkmanager # Unneeded package from ucore-minimal
      - cockpit-podman # Unneeded package from ucore-minimal
      - moby-engine # Unneeded package from ucore-minimal
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: chezmoi
    source: ghcr.io/exponentactivity/modules:latest
    # install: true # (Default - Expects type: boolean) Installs chezmoi to /usr/bin/chezmoi from latest Github release
    repository: "https://gitlab.com/unshippedreminder/dotfiles-server.git" # (Expects type: string) Git repository to initialize
    # enable_all_users: true # (Default - Expects type: boolean) Enable the modules services globally for all users
    # run_every: '1d' # (Default - Expects type: string) Dotfiles will be updated with this interval
    # wait_after_boot: '5m' # (Default - Expects type: string) Dotfile updates will wait this long after a boot before running
    # disable_init: false # (Default - Expects type: boolean) Disable the service that initializes `repository` on users that are logged in or has linger enabled
    # disable_update: false # (Default - Expects type: boolean) Disable the timer that updates chezmoi with the interval set above

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
